version: '3.1'

services:

  db:
    container_name: postgres
    image: postgres:alpine
    restart: always
    networks:
      - network
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

  migrate:
    container_name: migrate
    image: migrate/migrate
    networks:
      - network
    volumes:
      - ./migrations:/migrations
    entrypoint: migrate
    command: -path /migrations -database ${POSTGRESQL_URL} -verbose up
    links: 
      - db
    depends_on:
      db:
        condition: service_healthy
  
networks:
  network:
    name: network
    driver: bridge
